name: Reading Time
version: 2.0.0
description: "Estimated reading time plugin for Flextype"
author:
  name: Sergey Romanenko
  email: sergey.romaneko@flextype.org
  url: https://flextype.org
icon:
  name: clock
  set: bootstrap
homepage: https://github.com/flextype-plugins/reading-time
bugs: https://github.com/flextype-plugins/reading-time/issues
license: MIT
